-- ============================================================
-- TECH TRIATHLON ROUND 1 COIN TRACKER — SUPABASE DATABASE SCHEMA
-- Free, high-performance PostgreSQL schema for 30+ concurrent users
-- ============================================================

-- 1. Create Teams Table
CREATE TABLE IF NOT EXISTS public.teams (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  past INT NOT NULL DEFAULT 9,
  present INT NOT NULL DEFAULT 6,
  future INT NOT NULL DEFAULT 4,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Stalls Table
CREATE TABLE IF NOT EXISTS public.stalls (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  min_wager INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Matches Table
CREATE TABLE IF NOT EXISTS public.matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time BIGINT NOT NULL,
  stall_id TEXT NOT NULL,
  stall_name TEXT NOT NULL,
  team_a_id TEXT NOT NULL,
  team_a_name TEXT NOT NULL,
  team_b_id TEXT NOT NULL,
  team_b_name TEXT NOT NULL,
  wager INT NOT NULL,
  coin_type TEXT NOT NULL,
  result_a TEXT NOT NULL,
  result_b TEXT NOT NULL,
  change_a INT NOT NULL,
  change_b INT NOT NULL,
  conductor TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stalls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- 5. Create Permissive Access Policies (Public read/write with anon key)
DROP POLICY IF EXISTS "Allow public read teams" ON public.teams;
DROP POLICY IF EXISTS "Allow public write teams" ON public.teams;
CREATE POLICY "Allow public read teams" ON public.teams FOR SELECT USING (true);
CREATE POLICY "Allow public write teams" ON public.teams FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read stalls" ON public.stalls;
DROP POLICY IF EXISTS "Allow public write stalls" ON public.stalls;
CREATE POLICY "Allow public read stalls" ON public.stalls FOR SELECT USING (true);
CREATE POLICY "Allow public write stalls" ON public.stalls FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read matches" ON public.matches;
DROP POLICY IF EXISTS "Allow public write matches" ON public.matches;
CREATE POLICY "Allow public read matches" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Allow public write matches" ON public.matches FOR ALL USING (true) WITH CHECK (true);

-- 6. Enable Realtime Sync across all tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.teams, public.stalls, public.matches;

-- 7. Add Indexes for high-speed concurrent queries
CREATE INDEX IF NOT EXISTS idx_matches_time ON public.matches (time DESC);
CREATE INDEX IF NOT EXISTS idx_matches_team_a ON public.matches (team_a_id);
CREATE INDEX IF NOT EXISTS idx_matches_team_b ON public.matches (team_b_id);
